from pygame.event import custom_type

UI_BUTTON_ON_ENTER = custom_type()
UI_BUTTON_ON_LEAVE = custom_type()
UI_BUTTON_ON_CLICK = custom_type()
UI_BUTTON_ON_RELEASE = custom_type()

UI_SWITCH_ON_ENTER = custom_type()
UI_SWITCH_ON_LEAVE = custom_type()
UI_SWITCH_ON_CLICK = custom_type()
UI_SWITCH_ON_RELEASE = custom_type()

UI_TIMER_ON_ENTER = custom_type()
UI_TIMER_ON_LEAVE = custom_type()
UI_TIMER_ON_CLICK = custom_type()
UI_TIMER_ON_RELEASE = custom_type()

UI_EASTER_EGG = custom_type()

COLOR_BUTTON_DEFAULT = '#EDAAAE'
COLOR_BUTTON_HOVER = '#FFC9CC'
COLOR_BUTTON_PRESSED = '#E2B3B8'
COLOR_TIMER_DEFAULT = COLOR_BUTTON_DEFAULT

COLOR_BACKGROUND_DEFAULT = '#FFB6B9'
COLOR_BACKGROUND_WIN = '#E3BEC6'
COLOR_BACKGROUND_PAUSE = '#E3BEC6'

COLOR_FIELD_BACKGROUND = '#FAE3D9'

COLOR_TEXT = '#4C2717'
COLOR_LOGO = COLOR_TEXT
COLOR_DISPLAY = COLOR_TEXT

COLOR_CELL_SELECTED = '#61C0BF'
COLOR_CELL_NEIGHBOUR = '#BBDED6'
COLOR_CELL_HIGHLIGHTED = '#92E59C'
COLOR_CELL_HIGHLIGHTED_2 = '#B6EFBB'

COLOR_DIGIT_DEFAULT = '#3D86CE'
COLOR_DIGIT_CONFLICT = '#FF5E5E'
COLOR_DIGIT_INCORRECT = '#FF785E'
COLOR_DIGIT_FIXED = '#4C2717'

COLOR_MARK_DEFAULT = '#282828'
COLOR_MARK_HIGHLIGHTED = COLOR_CELL_HIGHLIGHTED

COLOR_HINT_BG = COLOR_BUTTON_PRESSED
COLOR_HINT_FRAME = COLOR_TEXT
